apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ashura-db-statefulset
spec:
  serviceName: "ashura-db-statefulset"
  replicas: 1
  selector:
    matchLabels:
      app: ashura-db # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: ashura-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          envFrom:
            - configMapRef:
                name: ashura-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ashura-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
            initialDelaySeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
            initialDelaySeconds: 5
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: ashura-db-service
spec:
  selector:
    app: ashura-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP



